equipment = {
    "weapon",
    "shield",
    "helmet",
    "body",
    "hands",
    "legs",
    "feet",
    "ring",
    "acc",
}

stats = {
    "maxHp",
    "maxMp",
    "might",
    "intelligence",
    "vitality",
    "armor",
    "resistance",
    "hit",
    "dodge",
    "crit",
    "luck",
}

extraStats = {
    "hpRegen",
    "mpRegen",
    "xpGain",
    "gpGain",
    "itemGain",
    "block",
    "parry",
    "deflect",
    "lightDamage",
    "lightResistance",
    "darkDamage",
    "darkResistance",
    "fireDamage",
    "fireResistance",
    "earthDamage",
    "earthResistance",
    "airDamage",
    "airResistance",
    "waterDamage",
    "waterResistance",
}